apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps

spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: myproject
  path: ./apps/myproject/prod
  prune: true
  postBuild:
    substitute:
      NGINX_IMAGE: nginx:1.19.6